# Generated by Django 4.2.4 on 2023-08-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="data",
            new_name="MlData",
        ),
    ]
